on:
  release:
    types: [released]

name: Build

jobs:
  build:
    uses: CoLearn-Dev/colink-protocol-inventory-workflow-templates/.github/workflows/docker.yml@main
    with:
      protocol_name: greetings-docker
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
